# Generated by Django 5.1.7 on 2025-04-02 18:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=255)),
                ("transaction_data", models.JSONField()),
                (
                    "fetched_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "fetched_date"],
                        name="emailparser_user_id_de1466_idx",
                    ),
                    models.Index(
                        fields=["transaction_id"], name="emailparser_transac_4e1e27_idx"
                    ),
                ],
                "unique_together": {("user", "transaction_id")},
            },
        ),
    ]
