# Generated by Django 5.1.7 on 2025-04-02 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bank_to_track",
                    models.CharField(
                        choices=[
                            ("HDFC", "HDFC Bank"),
                            ("ICICI", "ICICI Bank"),
                            ("SBI", "State Bank of India"),
                            ("AXIS", "Axis Bank"),
                            ("KOTAK", "Kotak Mahindra Bank"),
                            ("OTHER", "Other/Not Listed"),
                        ],
                        default="HDFC",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
